### ISSUE TITLE
OLA (BA : RET12, 14) - Compliance check

### ISSUE THREAD

**Issue by Jagannath-wits** [ONDC-Official/v1.2.0-logs#3111]
# Olamoney BA
### search
- Static terms is not required as they are not enabled yet.

### On_search_full_catalog
- bpp/fulfillments and bpp/providers.fulfillments don’t match i.e id, and no. of fulfillments; Buyer-elivery added in bpp/providers.fulfillments
- Circle.radius.value should be less than or equal to 500kms
- serviceability not captured properly i.e serviceability.category key is missing
- Invalid HSN code provided i.e 66211330 for item with id 84c3489b-b7df-481a-b3b3-280298734f36; please validate for others.

### On Init
- message/order/payment must have required property '@ondc/org/buyer_app_finder_fee_type’ and buyer_app_finder_fee_amount
- Invalid format for tax_number
- provider_tax_number must be present

### On Select out of stock
- quote/breakup/1 must have required property 'title'
- breakup/1/price/value Price value should be a number in string with upto 2 decimal places
- "Item's unit price missing in quote.breakup for item id c43cc392-9be0-4bd1-8595-c00afddb44fe"

### Cancel
- Cancellation reason id is not a valid reason id (buyer app initiated)

### On Cancel
- message/order must have required property 'billing'
- message/order/fulfillments/0 must be object"
- cancelled_by entity should be same as context/bap_id
- Reason ID and Delivery Object is mandatory field for on_cancel
- Reason id is different in cancellation object of /on_cancel from /cancel
- Initiated_by is mandatory field for on_cancel

### on status delivered
- message/order/fulfillments/1 must have required property 'id'
- message/order/fulfillments/1/tags/0/list/2 must have required property 'value'
- Initiated_by is mandatory field for on_status_rto_delivered/disposed
- fulfillment type rto end/time is missing in /on_status_rto_delivered/disposed

### On Update Delivered
- Missing payment/@ondc/org/settlement_details as compare to the previous calls or not captured correctly i.e. {\"settlement_counterparty\":\"buyer\",\"settlement_phase\":\"refund\",\"settlement_amount\":\"707.37\",\"settlement_type\":\"neft\"}
- on_update_delivered must have initiated_by code in fulfillments/tags/list
- Mismatch occur between the fulfillment Id of on_update_delivered 59d48b76-a6a4-4f16-a92d-7c6588b0a8bd and fulfillment Id of update_reverse_qc 4d5dae6a-664a-4311-a4de-fac1e3b5adf8
- start/time/timestamp of return fulfillment should be in the valid time/range as in on_update_approval
Fulfillments/Cancel/tags/quote_trail is missing in on_update_delivered

@op23singh2

**Comment by FarheenNazz** [comment]
OLA BA(RET 12)
## Flow- 4
### On_search-
- bpp/providers/id-pramaan_provider_1/locations.address must NOT have additional properties (building).
- bpp/providers/id-pramaan_provider_2/locations/0/address must NOT have additional properties (country)",
 - bpp~1providers/0/items/0/tags/1/list/1 must have required property 'value'",
                
- STD code does not match with correct area_code on /on_search.
- Fulfillments.gps- there should not be any gaps in between long and lat.
 - bpp/descriptor-accept_bap_terms is not required in bpp/descriptor/tags for now.
- bpp/descriptor-collect_payment is not required in bpp/descriptor/tags for now .
          
### select-
- City code mismatch in /on_search and /select.

 ### init-
- City code mismatch in /search and /init.
- Fulfillments.location.address-value of address.name, address.building and address.locality    should be unique.
      
  ### on_init-
 - payment must have required property '@ondc/org/settlement_details'.
 - message.order.cancellation_terms' in /message/order should not be provided as those are not enabled yet.
  - payment settlement_details missing in /on_init",
   - 'provider_tax_number' should have a valid PAN number format"
                      
### confirm-
- Buyer App Finder fee can't change from /search.
- tags/bap_terms-static_terms is not required for now! in confirm"
         

### on_confirm-
- message.order.tags.list-Number of digits in provider tax number in  message.order.tags[0].list should be 10.

            
### cancel-
- City code mismatch in /search and /cancel.
- Cancellation reason id is not a valid reason id (buyer app initiated).
           

### on_cancel-
- message/order must have required property 'billing'.
- fulfillments- must be an object and should not be null.
- payment must have required property '@ondc/org/settlement_details'.
- City code mismatch in /search and /on_cancel.
- Invalid CancellationID 999 or not allowed for SNP",
- cancelled_by entity should be same as context/bap_id",
- Reason _ID is mandatory field for on_cancel",
- Initiated_by is a mandatory field for on_cancel.
           
        
@op23singh2

**Comment by FarheenNazz** [comment]
# OLA BA (RET 12) Flow - 4

Buyer app should NACK for validations mentioned below


## On_Search

- STD code does not match with correct area_code on /on_search.
- Fulfillments.gps - there should not be any gaps in between longitude and latitude.
- Fulfillments.location.address - value of address.name, address.building, and address.locality should be unique.

## On_Init

- Payment must have required property @ondc/org/settlement_details.
- message.order.cancellation_terms in /message/order should not be provided as those are not enabled yet.
- Payment settlement_details missing in /on_init.
- provider_tax_number should have a valid PAN number format.


## Confirm
- Buyer App Finder fee can't change from /search.

## On_Confirm

- message.order.tags.list - Number of digits in provider tax number in message.order.tags[0].list should be 10.

## Cancel

- City code mismatch in /search and /cancel.
- Cancellation reason ID is not a valid reason ID (buyer app initiated).

## On_Cancel

- /message/order must have required property billing.
- fulfillments - must be an object and should not be null.
- Payment must have required property @ondc/org/settlement_details.
- City code mismatch in /search and /on_cancel.
- Invalid CancellationID 999 or not allowed for SNP.
- cancelled_by entity should be the same as context/bap_id.
- Reason_ID is a mandatory field of cancellation object for /on_cancel.
- Initiated_by is a mandatory field of cancellation object for /on_cancel.


@op23singh2

**Comment by sandeepshahi** [comment]
@op23singh2 @Anoopsmohan, Please resolve the issues identified by the utility. There are additional attributes in several objects, such as /billing and /fulfillments. Refer to the contract for all valid attributes, SNPs will ignore these extra attributes, potentially leading to the loss of important information.

Additionally, previously identified issues remain unresolved—for example, the GPS precision issues.

Do submit the utility report along with the logs.

**Comment by op23singh2** [comment]
Hi Sandeep,
Regarding those errors we discussed with Simran and we corrected few of
them which are mentioned by Simran. And we are told to ignore remaining
errors by Simran as they are optional and seller side errors.

Thanks and Regards
Onkar

**Comment by sandeepshahi** [comment]
@op23singh2, please resolve all the issues on the buyer app side. All of them need to be fixed.

**Comment by simranOndc** [comment]
select-
fulfillments.end.location.gps latitude and longitude must be provided with up to 6 digits each.

init -
Fulfillments.location.address - value of address.name, address.building, and address.locality should be unique.(check whole address object)

confirm
fulfillments.TAT is missing in this call.

@op23singh2 These issues are still there in your logs, Please make sure, above mentioned buyer side issues are resolved.

**Comment by murariyadav5** [comment]
@simranOndc  this is the updated PR 
https://github.com/ONDC-Official/v1.2.0-logs/pull/3180
can you please verify this, all the issues you mentioned here fixed.

**Comment by Anoopsmohan** [comment]
@simranOndc @sandeepshahi please close this asap.

**Comment by Jagannath-wits** [comment]
@op23singh2 Logs approved for OLA BA : RET12

**Comment by murariyadav5** [comment]
@Jagannath-wits Can you please let me know about ONDC:RET14 logs too

**Comment by Jagannath-wits** [comment]
@op23singh2 Logs approved for OLA BA : RET14
