### ISSUE TITLE
ShopEG - compliance check

### ISSUE THREAD

**Issue by sahil-ondc** [ONDC-Official/v1.2.0-logs#92]
**on_search_full_catalog_refresh**

- /message/catalog/bpp/providers/fulfillments/contact must have required property 'phone'
- /message/catalog/bpp/providers/descriptor must have required property 'long_desc'
- /message/catalog/bpp/providers/items/@ondc/org/statutory_reqs_packaged_commodities must have required property one of 'manufacturer_or_packer_address', 'common_or_generic_name_of_commodity', 'month_year_of_manufacture_packing_import'
- /message/catalog/bpp/providers/items/@ondc/org/statutory_reqs_prepackaged_food must have required property one of 'nutritional_info', 'other_FSSAI_license_no', 'importer_FSSAI_license_no'
- @ondc/org/contact_details_consumer_care should be in the format \"name,email,contactno\" in /bpp/ providers[0]/items
- item_id: 4daf0ef6-520a-4622-aa74-5853fba91345 should have veg_nonveg one of the 'veg', 'non_veg', 'egg'

**search_inc_refresh**

- context/city should be "\*" while sending search_inc_catalog request

**on_search_inc_refresh**

- Transaction Id for /search_inc_refresh and /on_search_inc_refresh api should be same
- Message Id for /search_inc_refresh and /on_search_inc_refresh api should be same
- bpp/fulfillments sent in payload shoulnd't be part of /on_search_inc_refresh api
- bpp/descriptor sent in payload shoulnd't be part of /on_search_inc_refresh api

**on_init**

- /message/order must have required property 'tags'

**on_confirm**

- /message/order/fulfillments/end must have required property 'time'

**on_status_delivered**

- /message/order/fulfillments must have required property '@ondc/org/TAT'
- /message/order/fulfillments/end/instructions must have required property 'code'

**common**

- /message/order/payment must have required property '@ondc/org/settlement_basis'
- /message/order/payment must have required property '@ondc/org/settlement_window'
- /message/order/payment must have required property '@ondc/org/withholding_amount'

@BasanthVerma

**Comment by BasanthVerma** [comment]
@sharmasahil0331 All comments have been addressed except for the common payment fields, since reference buyer app doesn't send these fields. If buyer app sends them then it's included in our response.

```
/message/order/payment must have required property '@ondc/org/settlement_basis'
/message/order/payment must have required property '@ondc/org/settlement_window'
/message/order/payment must have required property '@ondc/org/withholding_amount'
```

**Comment by sharmasahil0331** [comment]
**search_inc_refresh**

- /context, /message, /intent or /message/intent is missing or empty

**on_search_full_catalog_refresh**

- available count can't be greater than maximum count for item id: 7abbe7ca-1728-4993-82b7-6e17e001854f
- invalid reverse geocoding of gps provided in /message/catalog/bpp/providers/locations/gps

@BasanthVerma

**Comment by BasanthVerma** [comment]
**search_inc_refresh**
- Pasted the wrong log will send the right JSON

 **on_search_full_catalog_refresh**
- Looks correct. Available count (Stock count at the store), Maximum count (how many items can a customer select in a single order). So Available would always be greater than or equal to Maximum count. What are we missing?
- They are test shops so the address attributes can be dummy. Are any of the attribute value formats invalid that need fixing?  

@sharmasahil0331 

Will update search_inc_refresh on confirmation.

**Comment by sharmasahil0331** [comment]
@BasanthVerma Reported issues are still not fixed.

- A valid address with a valid GPS needs to be submitted. 
- /message/catalog/bpp/providers/items/quantity/available/count must be equal to one of the allowed values (99,0)
- /message/catalog/bpp/providers/items/quantity/maximum/count must be equal to one of the allowed values (99,0)
(The actual inventory count can't be provided and updated accurately. Here the available count only indicates whether the item is available in the inventory (99 means available and 0 means out of stock))

**Comment by BasanthVerma** [comment]
@sharmasahil0331 @bluecypher, we've submitted Group B with all 5 flows in #280

**Comment by sahil-ondc** [comment]
## Flow 1

**on_search_full_catalog_refresh**

- /message/catalog/bpp/providers/locations/address must have required property 'street'
- /message/catalog/bpp/providers/items/@ondc/org/statutory_reqs_prepackaged_food must have required property 'other_FSSAI_license_no'
- /message/catalog/bpp/providers/items/descriptor must have required property 'symbol'
- /message/catalog/bpp/providers/items/@ondc/org/statutory_reqs_prepackaged_food must have required property 'importer_FSSAI_license_no'
- /message/catalog/bpp/providers/items/@ondc/org/statutory_reqs_prepackaged_food must have required property 'other_FSSAI_license_no'
- /message/catalog/bpp/providers/items/@ondc/org/statutory_reqs_prepackaged_food must have required property 'importer_FSSAI_license_no'
- /message/catalog/bpp/providers/items/descriptor must have required property 'images'

**on_search_inc_catalog_refresh**

- provider id: 7d5U7O4owr8Pzzw5hiiY in bpp/providers didn't matched for providers id of /on_search_full_catalog_refresh

## Other Flows

- Timestamp for /on_search api cannot be greater than to /select api 'FLOWS SHOULD BE SUBMITTED IN SEQUENCIAL ORDER'

@BasanthVerma

**Comment by sahil-ondc** [comment]
# Group B

## Flow 1

### on_search_full_catalog_refresh

- /message/catalog/bpp/providers/locations/address must have required property 'street'
- /message/catalog/bpp/providers/items/@ondc/org/statutory_reqs_prepackaged_food must have required property 'other_FSSAI_license_no'
- /message/catalog/bpp/providers/items/@ondc/org/statutory_reqs_prepackaged_food must have required property 'importer_FSSAI_license_no'
- /message/catalog/bpp/providers/items/9/descriptor must have required property 'symbol'
- /message/catalog/bpp/providers/items/9/descriptor must have required property 'images'
- value passed in serviceability tags should be same as passed in location/circle
- either one of frequency, times or range should be provided in the /message/catalog/bpp/providers/locations

### on_search_inc_refresh

- provider id: 0Wd118zdPd6l0Wr1bhH2 in bpp/providers didn't matched for providers id of /on_search_full_catalog_refresh

## Flow 2

### on_select

- /message/order/quote/breakup/item/quantity available and maximum count logic should remain same as provided in on_search
  (99, 0)

### on_init

- /message/order/quote/breakup/item should be as per the API contract
  `https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit`

### on_status

- /message/order/fulfillments/0/end/instructions must have required property 'short_desc'
- Transaction Id should be same from /select onwards
- Order id in /confirm should match with on_status

## Flow 3

### on_select_out_of_stock

- /message/order/quote/breakup/item/quantity available and maximum count logic should remain same as provided in on_search
  (99, 0)
- /error object should have property message as per the API contract
  `https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit`

### on_init

- Same as Flow 2

## Flow 4

### on_cancel

- message/order/tags should have property quote_trail as per the API contract
  `https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit`
  
  @BasanthVerma

**Comment by sahil-ondc** [comment]
## Flow 1

### on_search_full_catalog_refresh

- /message/catalog/bpp/providers/categories/id should be unique id for custom category (across customization group, custom menu, variant group); alphanumeric & up to 12 characters

### on_search_inc_catalog_refresh

- /message/catalog/bpp/providers/items/@ondc/org/fssai_license_no cannot have value as empty string

## FLow 2

### on_status

- /message/order/fulfillments/0/end/instructions must have required property 'short_desc'

@BasanthVerma

**Comment by bluecypher** [comment]
@BasanthVerma,

Yes, both are fine.

**Comment by BasanthVerma** [comment]
@bluecypher Updated flow 1 logs, please check.

**Comment by sahil-ondc** [comment]
@BasanthVerma 

#### There should not be any manual change in the submitted logs, as we can check there is one commit after you have resubmitted the Flow 1, can you please clarify ?
<img width="1453" alt="Screenshot 2024-02-04 at 3 58 50 PM" src="https://github.com/ONDC-Official/v1.2.0-logs/assets/129926973/762deea5-3081-49a5-a09b-739feba2494e">

**Comment by BasanthVerma** [comment]
@sahil-ondc

I don't see our final commit here which shows the actual submission. 95c5386 and 69c0738 are our internal commits on the working branch of our fork. There can be n number of commits here. The final commit involves a merge from the working branch to our fork's master (which is missing in your screenshot). Then we make the actual submission by sending a PR from our fork's master to this repo's master.

<img width="1569" alt="Screenshot 2024-02-04 at 5 24 09 PM" src="https://github.com/ONDC-Official/v1.2.0-logs/assets/8429864/b365499e-c3de-4040-a8ea-a2f1afc612c9">

648df20 is the submission commit and no commits/changes were made after this.

Please check the full history.

@bluecypher

**Comment by sahil-ondc** [comment]
## Flow 1

### on_search_full

- 'accept_bap_terms' code should not be provided. It should be enabled when static terms are defined by the BNP and accepted by the seller app
- invalid property 'code' provided in /message/catalog/bpp/descriptor
- invalid property '@ondc/org/tat' provided in /message/catalog/bpp/providers/items
- invalid property 'product_master_uuid' provided in /message/catalog/bpp/providers/items
- invalid property 'hsn_code' provided in /message/catalog/bpp/providers/items
- invalid property 'contact_details_consumer_care_name' provided in /message/catalog/bpp/providers/items
- invalid property 'contact_details_consumer_care_contactno' provided in /message/catalog/bpp/providers/items
- placeholder values should not be provided in '@ondc/org/statutory_reqs_prepackaged_food'

### on_search_inc

- Similar Item as in /on_search_full_catalog_refresh api call, item id- 7864c546-d760-461e-bff1-3ebcd3b1799a (item with some change in delta should be sent in on_search_inc)

@BasanthVerma

**Comment by BasanthVerma** [comment]
@sahil-ondc @bluecypher resubmitted flow 1 new logs as per the above feedback here https://github.com/ONDC-Official/v1.2.0-logs/pull/768

Regarding the last point in on_search_full  - I understand that some of products had "na" under nutritional info, additives info etc so they appear as placeholder values but they're not. They were manually entered by one of our team members when creating those test products. We don't have placeholder values for any of such fields. However, although contract doesn't specify min length for such strings, we will be enforcing a min length of maybe 64 characters.

**Comment by bluecypher** [comment]
## Flow 1

**/on_search**

- "L2_category", "domain" are not a valid attributes in /items
- deprecated category ids should be avoided in /items/category_id; will be removed moved to different category over a period of time
- placeholder images of SKUs should not be provided in the catalog; ensure that all images are loading properly, as some are not currently loading
- "@ondc/org/TAT" is not a valid attribute in /items
- phone number in @ondc/org/contact_details_consumer_care should be of 10 or 11 digits
- unitized/measure/value should be used appropriately as per the SKU. For combo items, unit=1 can be used but proper measurement must be provided for unit items; eg: "cdd75c83-28c4-4b20-a1f2-7695a04275f0" can have following unitized/measure: unit = gram and value = 150
- invalid unitized/measure/value defined for certain SKUs; check; eg: 59e369f2-2bde-459e-97af-302c6bc7f4e2, refer to the above issue for the correct format

**/on_search (inc)**

- similar issues as in the full pull
- are all the scenarios of incremental pull supported?

## Flow 2

**/on_select**

- items/quantity is not required
- available/maximum count must be provided in quote/breakup for item types
- delivery tat "@ondc/org/TAT" can't be more than max of time_to_ship in on_search catalog

**/on_init**

- provider_location object is deprecated; use provider/locations[] instead

**/on_confirm**

- provider_tax_number and np_type must also be provided in /tags/bpp_terms

**/on_status**

- order state can't be In-progress when fulfillment state is Pending; refer to the [Fulfillment states & mapping to order states](https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.ii1xl1f08zho) section in the contract
- unsolicited call for Order-picked-up state must be provided
- actual pickup timestamp must be captured from "Order-picked-up" state and not "Out-for-delivery"
- check the invoice template as the values for unit price and total amount do not appear to be correct

## Flow 3

- similar issues as above

**/on_select (OOS)**

- error/code should be in string format

## Flow 4

- similar issues as above

**/on_cancel**

- invalid subscriber_id used in initiated_by; bap_id should be provided instead
- invalid code: "reason_code" in /fulfillments/tags/cancel_request; should be reason_id
- precancel_state must be provided in /fulfillments/tags

## Flow 5

- similar issues as above
- Invalid RTO flow; on_cancel is not as per the API contract

## Flow 6

- similar issues as above

**/on_update**

- reason_id should be used instead of reason_code
- adjustments in misc fee should also be provided in quote_trail
- message_id should be unique for every unsolicited call

**/on_status**

- refund details from /update must be appended in the "@ondc/org/settlement_details" object in the subsequent APIs


@BasanthVerma

**Comment by BasanthVerma** [comment]
`placeholder images of SKUs should not be provided in the catalog; ensure that all images are loading properly, as some are not currently loading`: These image links are from CAAS database and the CAAS image bucket appears to be down. Some images still might not load in our new submission, we are planning to remove all external image URLs and use our CDN in the coming weeks (before going to prod).

`are all the scenarios of incremental pull supported?` : All scenarios except offers increment pull is supported. We've included provider and location incremental update cases in the new submission.

@bluecypher resubmitted all 6 flows with fixes.

**Comment by sahil-ondc** [comment]
### on_search_full_catalog_refresh

- /message/catalog/bpp/providers/items/quantity/unitized/measure/unit must be equal to one of the allowed values (unit,dozen,gram,kilogram,tonne,litre,millilitre)
- /message/catalog/bpp/providers/items/tags should have mandatory tag origin
- remove formatting from /message/catalog/bpp/providers/items/descriptor short_desc and long_desc

### init

- address.building should be more than 3 chars

### on_confirm

- /message/order/tags/bpp_terms should have 'provider_tax_number'

### on_status

- /message/order/fulfillments/0 must have required property '@ondc/org/TAT'
- /message/order/fulfillments/0/start/location/address must have required property 'locality'
- /message/order/fulfillments/0/start/location/address must have required property 'city'
- /message/order/payment/params must have required property 'transaction_id'

@BasanthVerma

**Comment by BasanthVerma** [comment]
on_search_full_catalog_refresh

- /message/catalog/bpp/providers/items/quantity/unitized/measure/unit must be equal to one of the allowed values (unit,dozen,gram,kilogram,tonne,litre,millilitre) & /message/catalog/bpp/providers/items/tags should have mandatory tag origin: `Looks like very old test data from our catalog, we'll remove them.`
- remove formatting from /message/catalog/bpp/providers/items/descriptor short_desc and long_desc: `we'll remove them.`

init

address.building should be more than 3 chars - ` this is from buyer app`

on_confirm

/message/order/tags/bpp_terms should have 'provider_tax_number' - `We're MSN, in contract its says mandatory for ISN. Please confirm if it's still made necessary by buyer apps, we can add it.`

on_status -` Couldn't find any of these issues in the most of the on_status that I just checked. Please share the file path where these issues were found.`

@sahil-ondc @bluecypher Please check

**Comment by bluecypher** [comment]
provider_tax_number is mandatory for all the SNPs


@BasanthVerma

**Comment by BasanthVerma** [comment]
@bluecypher can you check my other comments too?

**Comment by BLR-0118** [comment]
@BasanthVerma - pls resubmit for flows 1 & 5 (expect above issues for flow 2 to be verifiable in flow 5);

**Comment by BasanthVerma** [comment]
@BLR-0118 please review our PR #949 , this includes the updates as per the feedback:

- on_search - Improved quality in catalog (Please ignore some broken image URLs, as they're from CAAS. We will be migrating them to our CDN before going to prod.)
- on_select - fulfillment.type added
- on_select - TAT is the maximum time set at the store level. They can deliver sooner than this since it's nearby. This was a test store. Since our sellers are hyperlocal - grocery - in most cases TAT will be around 12-24H in prod.
- tracking - as discussed this was required for F&B. We're supporting grocery and BPC for now with self-delivery by merchants. 
-  on_confirm - provider_tax_number added
- on_cancel - quote trail fixed. Delivery fee isn't refunded for RTO and removed from quote_trail. So delivery fee and conv fee with respect to delivery fee remain in breakup.quote.
- We've also fixed message_id for update / on_update. We can also submit flow 6 if needed.

**Comment by sahil-ondc** [comment]
## Flow 1

### on_search_full_catalog

- /message/catalog/bpp/providers must have required property 'time'
- /message/catalog/bpp/providers/locations/time must have required property 'timestamp'
- /message/catalog/bpp/providers/2/locations/0/time must have required property 'label'

### on_search_inc_catalog

- /context/message_id should be unique for every unsolicited on_search (provided same for store_on_search, provider_on_search)

@BasanthVerma

**Comment by BasanthVerma** [comment]
on_search_full_catalog - fixing 
on_search_inc_catalog - this appears to be correct. message_id's are unique in the submitted logs for catalog. But in store and provider it's not unique, fixing it.

@sahil-ondc

**Comment by BasanthVerma** [comment]
@BLR-0118 @bluecypher @sahil-ondc we've resubmitted flow 1 with feedback fixes

**Comment by sandeepshahi** [comment]
## Flow 1

**/on_search**

- range can be utilized instead of frequency and times in case of fixed timings
- description of variant grouping should not point to a particular variant; eg: 200g is mentioned in the description of variant_group "vg2"

**/on_search (inc)**

- context/timestamp can't be the same as in /search
- inc store/provider: time/timestamp can't be future dated; should be <= context/timestamp

## Flow 5

**/on_init**

- available and maximum count of items (quote/breakup/item/quantity) are not required in /on_init and onwards

**/on_status (OFD)**

- order pickup timestamp should not change in /fulfillments/start/time/timestamp; must remain the same as in Order-picked-up state

**/on_cancel**

- context/message_id should be unique; must not be the same as in /confirm
- delivery attempts (retry_count) is usually 3 as per the industry standards; Pls check if 2 is also followed
- updated_at timestamp of precancel_state is not captured correctly; should be the timestamp when the fulfillment state just before cancellation was triggered
- "misc" charges (convenience fee) are not adjusted properly in quote_trail; check previous and new quote/breakup

**/on_status (RTO-Delivered)**

- unsolicited call must be triggered for RTO Delivered/Disposed states


@BasanthVerma

**Comment by BasanthVerma** [comment]
on_search

1. range can be utilised instead of frequency and times in case of fixed timings - `The logs already appear to have range, along with frequency & times. Are you suggesting we only use range and remove frequency & times?`

2. description of variant grouping should not point to a particular variant; eg: 200g is mentioned in the description of variant_group "vg2" - `Contract example has "Variant Group 1". Is this something that is displayed to the end user on buyer apps? What is the recommended value to be used for the description? For ex: Surf excel 100 gm and 200 gm variants - can the description be "Quantity Measure based variant" or should it say "Surf excel" alone? `

on_cancel

3. delivery attempts (retry_count) is usually 3 as per the industry standards; Pls check if 2 is also followed - `In our case it's off-network self-fulfilled logistics where the merchant would be making the delivery themselves. Usually the merchant will try to contact the buyer before going out for delivery to check their availability. In practice they might reach out more than 2-3 times before canceling (additionally our ops will also attempt to contact in case the merchant couldn't reach the buyer). So should we leave this to 2 or set it to 3?`

@sandeepshahi @BLR-0118

**Comment by sahil-ondc** [comment]
## Flow 1

### on_search_full_catalog

- /message/catalog/bpp/descriptor/tags/bpp_terms should not have property 'collect_payment' as part of phase 1
- timming should be provided in provider level tags as per the API contract

## Flow 5

### on_cancel

- if there is any additional charges added due to RTO, that should be mentioned in quote trail as well

## Note

- Categories had some issues and are removed in the current logs, are those issues fixed (on_search)

@BasanthVerma

**Comment by BasanthVerma** [comment]
### on_search full catalog

1. /message/catalog/bpp/descriptor/tags/bpp_terms should not have property ‘collect_payment’ as part of phase 1
`Removing this`

2. timming should be provided in provider level tags as per the API contract
`Adding this as per the full contract`

3. Categories had some issues and are removed in the current logs, are those issues fixed (on_search)
`No categories are not removed. They’re fixed and are they’re part of the log that is submitted. (Provider ID nynGrPkGHzKUiR64S3Mw) `

### on_cancel

4. if there is any additional charges added due to RTO, that should be mentioned in quote trail as well
`There are no additional charges. quote_trail and quote values are adding up in the log submitted. Original Order delivery fee and the convenience fee with respect to the delivery fee is left in quote, rest are refunded in quote_trail. What are we missing here?`

**Comment by BasanthVerma** [comment]
@sahil-ondc

**Comment by sahil-ondc** [comment]
4. Some amount of misc is refunded and some amount is not refunded, what is the logic behind that ?

**Comment by BasanthVerma** [comment]
@sahil-ondc it's the convenience fee w.r.t delivery fee that is remaining in quote, more details below:

Convenience fee / misc = (SUM of items + Delivery fee ) * 3% convenience fee * 18% GST 

misc in on_confirm = (75+228+44.65) * 0.03 * 1.18 = 12.31 as shown in quote

revised misc for RTO on_cancel = ( 0+0+44.65) * 0.03 * 1.18 =  1.58 as shown in quote (Rest of the misc 10.73 with respect to items is is refunded in quote_trail)

**Comment by sahil-ondc** [comment]
ACK

**Comment by BasanthVerma** [comment]
@sahil-ondc fixed and resubmitted latest logs for on_search full catalog

**Comment by BLR-0118** [comment]
Flow 1
====
1. item unitized measure should be correctly defined (see comments on 23/2 above), e.g.:
- item 2aa56627-4f4e-4803-8ce4-4543a012dfc7 should have unitized measure of 22 gram (as per descriptor), not 1 unit;
- item 44ac7930-d8e3-4d26-8dc9-16a8b8461564 should have unitized measure of 500 gram;

Flow 5
====
1. /on_status APIs:
- to enable buyer apps to differentiate between hyperlocal & intercity fulfillment states, pls set routing.type to P2P (hyperlocal) or P2H2P (intercity), preferably when order is accepted;

2. /on_cancel:
- RTO has 2 states: RTO-Initiated & RTO-Delivered: you need to generate both events;
- pls also send start & end locations for RTO fulfillment as many buyer apps have validations on that;

**Comment by BLR-0118** [comment]
@BasanthVerma - request to pls resubmit for flow 1 & 5

**Comment by BLR-0118** [comment]
@BasanthVerma - removed the comment on rto states, it's available in /on_cancel & /on_status

**Comment by BasanthVerma** [comment]
@BLR-0118 Fixed and resubmitted flow 1 and 5. Please review #1282

**Comment by sahil-ondc** [comment]
## Flow 5

### on_select

- Quoted Price in /on_select does not match with the total price of items in /select i.e price for the item mismatch in on_search and on_select

### on_init

- provider_tax_number and np_type must be present in bpp_terms

@BasanthVerma

**Comment by BasanthVerma** [comment]
on_select: If you are referring to the price of item 78dc6dba-f96f-4e0f-a832-def925fa41b6, it exists in incremental item on_search

on_init: Looks like new addition in on_init based on the comment in the contract, we'll add it and resubmit flow 5. 

@sahil-ondc

**Comment by sahil-ondc** [comment]
ACK.

**Comment by BLR-0118** [comment]
Flow 1
====
1. full_catalog_on_search:
- what does "open" for location 6879 mean? was this store closed previously? if so, where is it showing in logs?
- item 7a7928e5-59b5-4503-8b4b-88c71ac4d230 has 8 digit EAN code?

2. incremental search:
- usecase for item going out-of-stock?

**Comment by BLR-0118** [comment]
Flow 5
====
1. You need to generate both events RTO-Initiated & RTO-Delivered (in your case) / RTO-Disposed;
2. not clear from logs whether you're doing this;

**Comment by BLR-0118** [comment]
@BasanthVerma - clearing logs for v1.2.0 (RET10), subject to the above being fixed;

**Comment by BLR-0118** [comment]
@BasanthVerma - logs cleared for RET13;
